package panelView;

import model.Pelanggan;
import controller.PelangganControl;
import java.awt.Component;
import javax.swing.JOptionPane;
import exception.InputKosongException;
import exception.NoTeleponException;

public class PanelPelanggan extends javax.swing.JPanel {
    
    private PelangganControl pc = new PelangganControl();
    private Pelanggan p = null;
    String actionPelanggan = null;
    int idPelanggan = 0;
    private Component rootPane;
    
    public PanelPelanggan() {
        initComponents();
        
        setOpaque(false);
        showPelanggan();
        setComponentsPelanggan(false);        
        setEditDeleteButtonPelanggan(false);        
        clearTextPelanggan();
    }
    
    public void setComponentsPelanggan(boolean value){
        namaPelangganInputTextField.setEnabled(value);
        umurInputTextField.setEnabled(value);
        noTeleponInputTextField.setEnabled(value);
    }
    
    public void setEditDeleteButtonPelanggan(boolean value){
        barukanPelangganButton.setEnabled(value);
        hapusPelangganButton.setEnabled(value);
    }
    
    public void clearTextPelanggan(){
        namaPelangganInputTextField.setText("");
        umurInputTextField.setText("");
        noTeleponInputTextField.setText("");
        searchPelangganInputTextField.setText("");
    }
    
    public void showPelanggan(){
        pelangganTextArea.setText("Daftar Pelanggan di Apotek ASEAN : \n===================================\n\n" 
                + pc.showAllStringPelanggan());
    }
  
    private void doSearchPelanggan(){
        if(searchPelangganInputTextField.getText().isEmpty()){
            return;
        }
            
        // Nanti akan ditentukan sendiri di Control, inputannya String atau Integer
        p = pc.searchPelangganByAll(searchPelangganInputTextField.getText());
        
        if(p == null ){
            JOptionPane.showMessageDialog(rootPane, "Pelanggan Tidak Ditemukan!");
            return;
        }
        setEditDeleteButtonPelanggan(true);
        clearTextPelanggan();

        namaPelangganInputTextField.setText(p.getNama());
        umurInputTextField.setText(Integer.toString(p.getUmur()));
        noTeleponInputTextField.setText(p.getNotelp());

        idPelanggan = p.getId_pelanggan();
    }
    
    private void inputKosongPelangganException() throws InputKosongException{
        if(namaPelangganInputTextField.getText().isEmpty() || umurInputTextField.getText().isEmpty() || noTeleponInputTextField.getText().isEmpty())
            throw new InputKosongException();
    }
    
    private void noTeleponException() throws NoTeleponException{
        if(!noTeleponInputTextField.getText().matches("^\\+?[0-9]+$"))
            throw new NoTeleponException();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coverPanel = new javax.swing.JPanel();
        pelangganPanel = new javax.swing.JPanel();
        pelangganLabel = new javax.swing.JLabel();
        searchPelangganInputPanel = new javax.swing.JPanel();
        searchPelangganInputLabel = new javax.swing.JLabel();
        searchPelangganInputTextField = new javax.swing.JTextField();
        searchPelangganInputButton = new javax.swing.JButton();
        pelangganFormPanel = new javax.swing.JPanel();
        namaPelangganPanel = new javax.swing.JPanel();
        namaPelangganInputLabel = new javax.swing.JLabel();
        namaPelangganInputTextField = new javax.swing.JTextField();
        umurInputPanel = new javax.swing.JPanel();
        umurInputLabel = new javax.swing.JLabel();
        umurInputTextField = new javax.swing.JTextField();
        noTeleponInputPanel = new javax.swing.JPanel();
        noTeleponInputLabel = new javax.swing.JLabel();
        noTeleponInputTextField = new javax.swing.JTextField();
        simpanPelangganButton = new javax.swing.JButton();
        pelangganButtonPanel = new javax.swing.JPanel();
        tambahPelangganButton = new javax.swing.JButton();
        barukanPelangganButton = new javax.swing.JButton();
        hapusPelangganButton = new javax.swing.JButton();
        pelangganScrollPane = new javax.swing.JScrollPane();
        pelangganTextArea = new javax.swing.JTextArea();

        coverPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        pelangganPanel.setBackground(new java.awt.Color(134, 196, 66));

        pelangganLabel.setFont(new java.awt.Font("Arial Black", 1, 80)); // NOI18N
        pelangganLabel.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLabel.setText("PELANGGAN");

        searchPelangganInputPanel.setBackground(new java.awt.Color(134, 196, 6));

        searchPelangganInputLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        searchPelangganInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchPelangganInputLabel.setText("Pencarian Pelanggan");

        searchPelangganInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        searchPelangganInputTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchPelangganInputTextField.setForeground(new java.awt.Color(0, 0, 0));
        searchPelangganInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPelangganInputTextFieldActionPerformed(evt);
            }
        });
        searchPelangganInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchPelangganInputTextFieldKeyTyped(evt);
            }
        });

        searchPelangganInputButton.setBackground(new java.awt.Color(24, 170, 176));
        searchPelangganInputButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        searchPelangganInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPelangganInputButton.setText("Cari");
        searchPelangganInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPelangganInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPelangganInputPanelLayout = new javax.swing.GroupLayout(searchPelangganInputPanel);
        searchPelangganInputPanel.setLayout(searchPelangganInputPanelLayout);
        searchPelangganInputPanelLayout.setHorizontalGroup(
            searchPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPelangganInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPelangganInputPanelLayout.createSequentialGroup()
                        .addComponent(searchPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchPelangganInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(searchPelangganInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        searchPelangganInputPanelLayout.setVerticalGroup(
            searchPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPelangganInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPelangganInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPelangganInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchPelangganInputTextField)
                    .addComponent(searchPelangganInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pelangganFormPanel.setBackground(new java.awt.Color(134, 196, 66));
        pelangganFormPanel.setForeground(new java.awt.Color(255, 255, 255));

        namaPelangganPanel.setBackground(new java.awt.Color(134, 196, 66));
        namaPelangganPanel.setForeground(new java.awt.Color(255, 255, 255));

        namaPelangganInputLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        namaPelangganInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaPelangganInputLabel.setText("Nama Pelanggan");

        namaPelangganInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        namaPelangganInputTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        namaPelangganInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPelangganInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaPelangganPanelLayout = new javax.swing.GroupLayout(namaPelangganPanel);
        namaPelangganPanel.setLayout(namaPelangganPanelLayout);
        namaPelangganPanelLayout.setHorizontalGroup(
            namaPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPelangganInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaPelangganPanelLayout.setVerticalGroup(
            namaPelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPelangganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaPelangganInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPelangganInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        umurInputPanel.setBackground(new java.awt.Color(134, 196, 66));
        umurInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        umurInputLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        umurInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        umurInputLabel.setText("Umur");

        umurInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        umurInputTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout umurInputPanelLayout = new javax.swing.GroupLayout(umurInputPanel);
        umurInputPanel.setLayout(umurInputPanelLayout);
        umurInputPanelLayout.setHorizontalGroup(
            umurInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(umurInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(umurInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(umurInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(umurInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        umurInputPanelLayout.setVerticalGroup(
            umurInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(umurInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(umurInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umurInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        noTeleponInputPanel.setBackground(new java.awt.Color(134, 196, 66));
        noTeleponInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        noTeleponInputLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        noTeleponInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        noTeleponInputLabel.setText("No. Telepon");

        noTeleponInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        noTeleponInputTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        noTeleponInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTeleponInputTextFieldActionPerformed(evt);
            }
        });
        noTeleponInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noTeleponInputTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout noTeleponInputPanelLayout = new javax.swing.GroupLayout(noTeleponInputPanel);
        noTeleponInputPanel.setLayout(noTeleponInputPanelLayout);
        noTeleponInputPanelLayout.setHorizontalGroup(
            noTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noTeleponInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noTeleponInputPanelLayout.setVerticalGroup(
            noTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTeleponInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pelangganFormPanelLayout = new javax.swing.GroupLayout(pelangganFormPanel);
        pelangganFormPanel.setLayout(pelangganFormPanelLayout);
        pelangganFormPanelLayout.setHorizontalGroup(
            pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noTeleponInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                        .addGroup(pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(umurInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaPelangganPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pelangganFormPanelLayout.setVerticalGroup(
            pelangganFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganFormPanelLayout.createSequentialGroup()
                .addComponent(namaPelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(umurInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTeleponInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        simpanPelangganButton.setBackground(new java.awt.Color(24, 170, 176));
        simpanPelangganButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        simpanPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanPelangganButton.setText("Simpan");
        simpanPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPelangganButtonActionPerformed(evt);
            }
        });

        pelangganButtonPanel.setBackground(new java.awt.Color(134, 196, 66));

        tambahPelangganButton.setBackground(new java.awt.Color(24, 170, 176));
        tambahPelangganButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tambahPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahPelangganButton.setText("Tambah");
        tambahPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPelangganButtonActionPerformed(evt);
            }
        });

        barukanPelangganButton.setBackground(new java.awt.Color(24, 170, 176));
        barukanPelangganButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        barukanPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanPelangganButton.setText("Edit");
        barukanPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanPelangganButtonActionPerformed(evt);
            }
        });

        hapusPelangganButton.setBackground(new java.awt.Color(24, 170, 176));
        hapusPelangganButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        hapusPelangganButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusPelangganButton.setText("Hapus");
        hapusPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPelangganButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pelangganButtonPanelLayout = new javax.swing.GroupLayout(pelangganButtonPanel);
        pelangganButtonPanel.setLayout(pelangganButtonPanelLayout);
        pelangganButtonPanelLayout.setHorizontalGroup(
            pelangganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganButtonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pelangganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahPelangganButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barukanPelangganButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusPelangganButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pelangganButtonPanelLayout.setVerticalGroup(
            pelangganButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barukanPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hapusPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pelangganScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pelangganTextArea.setBackground(new java.awt.Color(255, 255, 255));
        pelangganTextArea.setColumns(20);
        pelangganTextArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pelangganTextArea.setForeground(new java.awt.Color(0, 0, 0));
        pelangganTextArea.setRows(5);
        pelangganScrollPane.setViewportView(pelangganTextArea);

        javax.swing.GroupLayout pelangganPanelLayout = new javax.swing.GroupLayout(pelangganPanel);
        pelangganPanel.setLayout(pelangganPanelLayout);
        pelangganPanelLayout.setHorizontalGroup(
            pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganPanelLayout.createSequentialGroup()
                .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pelangganPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanPelangganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pelangganPanelLayout.createSequentialGroup()
                                .addComponent(pelangganButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pelangganFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pelangganPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(pelangganLabel))
                    .addGroup(pelangganPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(searchPelangganInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(pelangganScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        pelangganPanelLayout.setVerticalGroup(
            pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pelangganScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pelangganPanelLayout.createSequentialGroup()
                        .addComponent(pelangganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(searchPelangganInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pelangganFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pelangganButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(simpanPelangganButton)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout coverPanelLayout = new javax.swing.GroupLayout(coverPanel);
        coverPanel.setLayout(coverPanelLayout);
        coverPanelLayout.setHorizontalGroup(
            coverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        coverPanelLayout.setVerticalGroup(
            coverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1304, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(coverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(coverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchPelangganInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPelangganInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPelangganInputTextFieldActionPerformed

    private void searchPelangganInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPelangganInputTextFieldKeyTyped
        if(evt.getKeyChar()=='\n'){
            doSearchPelanggan();
        }
    }//GEN-LAST:event_searchPelangganInputTextFieldKeyTyped

    private void searchPelangganInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPelangganInputButtonActionPerformed
        doSearchPelanggan();
    }//GEN-LAST:event_searchPelangganInputButtonActionPerformed

    private void barukanPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanPelangganButtonActionPerformed
        actionPelanggan = "update";
        setComponentsPelanggan(true);
    }//GEN-LAST:event_barukanPelangganButtonActionPerformed

    private void hapusPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPelangganButtonActionPerformed
        clearTextPelanggan();
        setEditDeleteButtonPelanggan(false);
        setComponentsPelanggan(false);

        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION){
            idPelanggan = -1;
            return;
        }

        pc.deleteDataPelanggan(idPelanggan);
        idPelanggan = -1;
        showPelanggan();
    }//GEN-LAST:event_hapusPelangganButtonActionPerformed

    private void tambahPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPelangganButtonActionPerformed
        actionPelanggan = "add";
        clearTextPelanggan();
        setEditDeleteButtonPelanggan(false);
        setComponentsPelanggan(true);
    }//GEN-LAST:event_tambahPelangganButtonActionPerformed

    private void namaPelangganInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPelangganInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPelangganInputTextFieldActionPerformed

    private void noTeleponInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTeleponInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTeleponInputTextFieldActionPerformed

    private void noTeleponInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noTeleponInputTextFieldKeyTyped

    }//GEN-LAST:event_noTeleponInputTextFieldKeyTyped

    private void simpanPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPelangganButtonActionPerformed
        // TODO add your handling code here:
        if(actionPelanggan == null)
        return;
        try{
            inputKosongPelangganException();
            noTeleponException();
            
            int dialog = JOptionPane.showConfirmDialog(rootPane, "Yakin ingin menambahkan Pelanggan?");
            if(dialog != JOptionPane.YES_OPTION) return;

            switch(actionPelanggan){
                case "add":
                    p = new Pelanggan(namaPelangganInputTextField.getText(), Integer.parseInt(umurInputTextField.getText()), noTeleponInputTextField.getText());
                    pc.insertDataPelanggan(p);
                    clearTextPelanggan();
                    setEditDeleteButtonPelanggan(false);
                    setComponentsPelanggan(false);
                    break;
                case "update":
                    p = new Pelanggan(namaPelangganInputTextField.getText(), Integer.parseInt(umurInputTextField.getText()), noTeleponInputTextField.getText());
                    pc.updateDataPelanggan(p, idPelanggan);
                    clearTextPelanggan();
                    setEditDeleteButtonPelanggan(false);
                    setComponentsPelanggan(false);
                    break;
                default:
                    break;
            }
            showPelanggan();
            actionPelanggan = null;
        }catch(InputKosongException | NoTeleponException e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Input Gaji Harus Berupa Angka!");
        }
    }//GEN-LAST:event_simpanPelangganButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanPelangganButton;
    private javax.swing.JPanel coverPanel;
    private javax.swing.JButton hapusPelangganButton;
    private javax.swing.JLabel namaPelangganInputLabel;
    private javax.swing.JTextField namaPelangganInputTextField;
    private javax.swing.JPanel namaPelangganPanel;
    private javax.swing.JLabel noTeleponInputLabel;
    private javax.swing.JPanel noTeleponInputPanel;
    private javax.swing.JTextField noTeleponInputTextField;
    private javax.swing.JPanel pelangganButtonPanel;
    private javax.swing.JPanel pelangganFormPanel;
    private javax.swing.JLabel pelangganLabel;
    private javax.swing.JPanel pelangganPanel;
    private javax.swing.JScrollPane pelangganScrollPane;
    private javax.swing.JTextArea pelangganTextArea;
    private javax.swing.JButton searchPelangganInputButton;
    private javax.swing.JLabel searchPelangganInputLabel;
    private javax.swing.JPanel searchPelangganInputPanel;
    private javax.swing.JTextField searchPelangganInputTextField;
    private javax.swing.JButton simpanPelangganButton;
    private javax.swing.JButton tambahPelangganButton;
    private javax.swing.JLabel umurInputLabel;
    private javax.swing.JPanel umurInputPanel;
    private javax.swing.JTextField umurInputTextField;
    // End of variables declaration//GEN-END:variables
}
