package panelView;

import model.Apoteker;
import controller.ApotekerControl;
import java.awt.Component;
import javax.swing.JOptionPane;
import exception.InputKosongException;

public class PanelApoteker extends javax.swing.JPanel {
    private ApotekerControl ac = new ApotekerControl();
    private Apoteker a = null;
    String actionApoteker = null;
    int idApoteker = 0;
    private Component rootPane;
  
    public PanelApoteker(Apoteker loginApoteker) {
        initComponents();
        
        namaLabel.setText(loginApoteker.getNama_apoteker());
        emailLabel.setText(loginApoteker.getEmail());
        
        setOpaque(false);
        showApoteker();
        setComponentsApoteker(false);        
        setEditDeleteButtonApoteker(false);        
        clearTextApoteker();
    }
    
    public void setComponentsApoteker(boolean value){
        namaApotekerInputTextField.setEnabled(value);
        gajiInputTextField.setEnabled(value);
        emailApotekerInputTextField.setEnabled(value);
    }
    
    public void setEditDeleteButtonApoteker(boolean value){
        barukanApotekerButton.setEnabled(value);
        hapusApotekerButton.setEnabled(value);
    }
    
    public void clearTextApoteker(){
        namaApotekerInputTextField.setText("");
        gajiInputTextField.setText("");
        emailApotekerInputTextField.setText("");
        searchApotekerInputTextField.setText("");
    }
    
    public void showApoteker(){
        apotekerTextArea.setText("Daftar Apoteker di Apotek ASEAN : \n===================================\n\n" 
                + ac.showAllStringApoteker());
    }
  
    private void doSearchApoteker(){
        if(searchApotekerInputTextField.getText().isEmpty()){
            return;
        }
            
        // Nanti akan ditentukan sendiri di Control, inputannya String atau Integer
        a = ac.searchApotekerByAll(searchApotekerInputTextField.getText());
        
        if(a != null){
            setEditDeleteButtonApoteker(true);
            clearTextApoteker();

            namaApotekerInputTextField.setText(a.getNama_apoteker());
            gajiInputTextField.setText(Integer.toString(a.getGaji()));
            emailApotekerInputTextField.setText(a.getEmail());

            idApoteker = a.getId_apoteker();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Apoteker Tidak Ditemukan!");
        }
    }
    
    private void inputKosongApotekerException() throws InputKosongException{
        if(namaApotekerInputTextField.getText().isEmpty() || gajiInputTextField.getText().isEmpty() || emailApotekerInputTextField.getText().isEmpty())
            throw new InputKosongException();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apotekerPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        apotekerLabel = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        apotekerIcon = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        searchApotekerInputPanel = new javax.swing.JPanel();
        searchApotekerInputLabel = new javax.swing.JLabel();
        searchApotekerInputTextField = new javax.swing.JTextField();
        searchApotekerInputButton = new javax.swing.JButton();
        apotekerFormPanel = new javax.swing.JPanel();
        apotekerButtonPanel = new javax.swing.JPanel();
        barukanApotekerButton = new javax.swing.JButton();
        hapusApotekerButton = new javax.swing.JButton();
        tambahApotekerButton = new javax.swing.JButton();
        namaApotekerPanel = new javax.swing.JPanel();
        namaApotekerInputLabel = new javax.swing.JLabel();
        namaApotekerInputTextField = new javax.swing.JTextField();
        gajiInputPanel = new javax.swing.JPanel();
        gajiInputLabel = new javax.swing.JLabel();
        gajiInputTextField = new javax.swing.JTextField();
        emailApotekerInputPanel = new javax.swing.JPanel();
        emailApotekerInputLabel = new javax.swing.JLabel();
        emailApotekerInputTextField = new javax.swing.JTextField();
        ketentuanPanel = new javax.swing.JPanel();
        ketentuanLabel = new javax.swing.JLabel();
        ketentuanLabel1 = new javax.swing.JLabel();
        ketentuanLabel2 = new javax.swing.JLabel();
        simpanApotekerButton = new javax.swing.JButton();
        apotekerScrollPane = new javax.swing.JScrollPane();
        apotekerTextArea = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        apotekerPanel.setBackground(new java.awt.Color(134, 196, 66));

        headerPanel.setBackground(new java.awt.Color(134, 196, 66));

        apotekerLabel.setFont(new java.awt.Font("Arial Black", 1, 80)); // NOI18N
        apotekerLabel.setForeground(new java.awt.Color(255, 255, 255));
        apotekerLabel.setText("APOTEKER ");

        profilePanel.setBackground(new java.awt.Color(24, 170, 176));

        apotekerIcon.setBackground(new java.awt.Color(255, 255, 255));
        apotekerIcon.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        apotekerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apotekerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Apoteker.png"))); // NOI18N

        namaLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLabel.setText("Nama_apoteker");

        emailLabel.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emailLabel.setText("email_apoteker");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(apotekerIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(apotekerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(namaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(apotekerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(apotekerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        searchApotekerInputPanel.setBackground(new java.awt.Color(134, 196, 6));

        searchApotekerInputLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        searchApotekerInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchApotekerInputLabel.setText("Pencarian Apoteker");

        searchApotekerInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        searchApotekerInputTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchApotekerInputTextField.setForeground(new java.awt.Color(0, 0, 0));
        searchApotekerInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchApotekerInputTextFieldActionPerformed(evt);
            }
        });
        searchApotekerInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchApotekerInputTextFieldKeyTyped(evt);
            }
        });

        searchApotekerInputButton.setBackground(new java.awt.Color(24, 170, 176));
        searchApotekerInputButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        searchApotekerInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchApotekerInputButton.setText("Cari");
        searchApotekerInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchApotekerInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchApotekerInputPanelLayout = new javax.swing.GroupLayout(searchApotekerInputPanel);
        searchApotekerInputPanel.setLayout(searchApotekerInputPanelLayout);
        searchApotekerInputPanelLayout.setHorizontalGroup(
            searchApotekerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchApotekerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchApotekerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchApotekerInputPanelLayout.createSequentialGroup()
                        .addComponent(searchApotekerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(searchApotekerInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 363, Short.MAX_VALUE))
                    .addComponent(searchApotekerInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        searchApotekerInputPanelLayout.setVerticalGroup(
            searchApotekerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchApotekerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchApotekerInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchApotekerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchApotekerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchApotekerInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        apotekerFormPanel.setBackground(new java.awt.Color(134, 196, 66));
        apotekerFormPanel.setForeground(new java.awt.Color(255, 255, 255));

        apotekerButtonPanel.setBackground(new java.awt.Color(134, 196, 66));

        barukanApotekerButton.setBackground(new java.awt.Color(24, 170, 176));
        barukanApotekerButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        barukanApotekerButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanApotekerButton.setText("Edit");
        barukanApotekerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanApotekerButtonActionPerformed(evt);
            }
        });

        hapusApotekerButton.setBackground(new java.awt.Color(24, 170, 176));
        hapusApotekerButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        hapusApotekerButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusApotekerButton.setText("Hapus");
        hapusApotekerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusApotekerButtonActionPerformed(evt);
            }
        });

        tambahApotekerButton.setBackground(new java.awt.Color(24, 170, 176));
        tambahApotekerButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tambahApotekerButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahApotekerButton.setText("Tambah");
        tambahApotekerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahApotekerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout apotekerButtonPanelLayout = new javax.swing.GroupLayout(apotekerButtonPanel);
        apotekerButtonPanel.setLayout(apotekerButtonPanelLayout);
        apotekerButtonPanelLayout.setHorizontalGroup(
            apotekerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apotekerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahApotekerButton)
                .addGap(18, 18, 18)
                .addComponent(barukanApotekerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(hapusApotekerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        apotekerButtonPanelLayout.setVerticalGroup(
            apotekerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apotekerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apotekerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hapusApotekerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(barukanApotekerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahApotekerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaApotekerPanel.setBackground(new java.awt.Color(134, 196, 66));
        namaApotekerPanel.setForeground(new java.awt.Color(255, 255, 255));

        namaApotekerInputLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        namaApotekerInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaApotekerInputLabel.setText("Nama Apoteker");

        namaApotekerInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        namaApotekerInputTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        namaApotekerInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaApotekerInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaApotekerPanelLayout = new javax.swing.GroupLayout(namaApotekerPanel);
        namaApotekerPanel.setLayout(namaApotekerPanelLayout);
        namaApotekerPanelLayout.setHorizontalGroup(
            namaApotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaApotekerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaApotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaApotekerInputTextField)
                    .addComponent(namaApotekerInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaApotekerPanelLayout.setVerticalGroup(
            namaApotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaApotekerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaApotekerInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaApotekerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gajiInputPanel.setBackground(new java.awt.Color(134, 196, 66));
        gajiInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        gajiInputLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        gajiInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        gajiInputLabel.setText("Gaji Apoteker");

        gajiInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        gajiInputTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout gajiInputPanelLayout = new javax.swing.GroupLayout(gajiInputPanel);
        gajiInputPanel.setLayout(gajiInputPanelLayout);
        gajiInputPanelLayout.setHorizontalGroup(
            gajiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gajiInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gajiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gajiInputTextField)
                    .addComponent(gajiInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gajiInputPanelLayout.setVerticalGroup(
            gajiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gajiInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gajiInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gajiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        emailApotekerInputPanel.setBackground(new java.awt.Color(134, 196, 66));
        emailApotekerInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        emailApotekerInputLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        emailApotekerInputLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailApotekerInputLabel.setText("Email Apoteker");

        emailApotekerInputTextField.setBackground(new java.awt.Color(255, 255, 255));
        emailApotekerInputTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        emailApotekerInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailApotekerInputTextFieldActionPerformed(evt);
            }
        });
        emailApotekerInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailApotekerInputTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout emailApotekerInputPanelLayout = new javax.swing.GroupLayout(emailApotekerInputPanel);
        emailApotekerInputPanel.setLayout(emailApotekerInputPanelLayout);
        emailApotekerInputPanelLayout.setHorizontalGroup(
            emailApotekerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailApotekerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emailApotekerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailApotekerInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailApotekerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        emailApotekerInputPanelLayout.setVerticalGroup(
            emailApotekerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailApotekerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emailApotekerInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailApotekerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        ketentuanPanel.setBackground(new java.awt.Color(134, 196, 66));

        ketentuanLabel.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        ketentuanLabel.setForeground(new java.awt.Color(255, 255, 255));
        ketentuanLabel.setText("* Username & Password akan ter-generate secara otomatis :");

        ketentuanLabel1.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        ketentuanLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ketentuanLabel1.setText("Username : NamaNama");

        ketentuanLabel2.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        ketentuanLabel2.setForeground(new java.awt.Color(255, 255, 255));
        ketentuanLabel2.setText("Password : Nama123");

        javax.swing.GroupLayout ketentuanPanelLayout = new javax.swing.GroupLayout(ketentuanPanel);
        ketentuanPanel.setLayout(ketentuanPanelLayout);
        ketentuanPanelLayout.setHorizontalGroup(
            ketentuanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ketentuanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ketentuanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ketentuanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ketentuanPanelLayout.createSequentialGroup()
                        .addComponent(ketentuanLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(ketentuanLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ketentuanPanelLayout.setVerticalGroup(
            ketentuanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ketentuanPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ketentuanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ketentuanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ketentuanLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketentuanLabel1))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout apotekerFormPanelLayout = new javax.swing.GroupLayout(apotekerFormPanel);
        apotekerFormPanel.setLayout(apotekerFormPanelLayout);
        apotekerFormPanelLayout.setHorizontalGroup(
            apotekerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apotekerFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(apotekerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apotekerFormPanelLayout.createSequentialGroup()
                        .addGroup(apotekerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gajiInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaApotekerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(apotekerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(apotekerFormPanelLayout.createSequentialGroup()
                                .addComponent(emailApotekerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apotekerFormPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ketentuanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(apotekerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        apotekerFormPanelLayout.setVerticalGroup(
            apotekerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apotekerFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apotekerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(apotekerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apotekerFormPanelLayout.createSequentialGroup()
                        .addComponent(namaApotekerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gajiInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(apotekerFormPanelLayout.createSequentialGroup()
                        .addComponent(emailApotekerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ketentuanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanApotekerButton.setBackground(new java.awt.Color(24, 170, 176));
        simpanApotekerButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        simpanApotekerButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanApotekerButton.setText("Simpan");
        simpanApotekerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanApotekerButtonActionPerformed(evt);
            }
        });

        apotekerScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        apotekerTextArea.setBackground(new java.awt.Color(255, 255, 255));
        apotekerTextArea.setColumns(20);
        apotekerTextArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        apotekerTextArea.setForeground(new java.awt.Color(0, 0, 0));
        apotekerTextArea.setRows(5);
        apotekerScrollPane.setViewportView(apotekerTextArea);

        javax.swing.GroupLayout apotekerPanelLayout = new javax.swing.GroupLayout(apotekerPanel);
        apotekerPanel.setLayout(apotekerPanelLayout);
        apotekerPanelLayout.setHorizontalGroup(
            apotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apotekerPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(apotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apotekerPanelLayout.createSequentialGroup()
                        .addComponent(searchApotekerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addGroup(apotekerPanelLayout.createSequentialGroup()
                        .addGroup(apotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(apotekerPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(apotekerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(apotekerPanelLayout.createSequentialGroup()
                                .addComponent(apotekerFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simpanApotekerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        apotekerPanelLayout.setVerticalGroup(
            apotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apotekerPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchApotekerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(apotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apotekerPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(simpanApotekerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(apotekerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apotekerFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apotekerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apotekerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apotekerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void searchApotekerInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchApotekerInputTextFieldKeyTyped
        if(evt.getKeyChar()=='\n'){
            doSearchApoteker();
        }
    }//GEN-LAST:event_searchApotekerInputTextFieldKeyTyped

    private void searchApotekerInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchApotekerInputButtonActionPerformed
        doSearchApoteker();
    }//GEN-LAST:event_searchApotekerInputButtonActionPerformed

    private void barukanApotekerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanApotekerButtonActionPerformed
        actionApoteker = "update";
        setComponentsApoteker(true);
    }//GEN-LAST:event_barukanApotekerButtonActionPerformed

    private void hapusApotekerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusApotekerButtonActionPerformed
        clearTextApoteker();
        setEditDeleteButtonApoteker(false);
        setComponentsApoteker(false);

        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION){
            idApoteker = -1;
            return;
        }

        ac.deleteDataApoteker(idApoteker);
        idApoteker = -1;
        showApoteker();
    }//GEN-LAST:event_hapusApotekerButtonActionPerformed

    private void tambahApotekerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahApotekerButtonActionPerformed
        actionApoteker = "add";
        clearTextApoteker();
        setEditDeleteButtonApoteker(false);
        setComponentsApoteker(true);
    }//GEN-LAST:event_tambahApotekerButtonActionPerformed

    private void namaApotekerInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaApotekerInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaApotekerInputTextFieldActionPerformed

    private void emailApotekerInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailApotekerInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailApotekerInputTextFieldActionPerformed

    private void emailApotekerInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailApotekerInputTextFieldKeyTyped
        
    }//GEN-LAST:event_emailApotekerInputTextFieldKeyTyped

    private void simpanApotekerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanApotekerButtonActionPerformed
        // TODO add your handling code here:
        if(actionApoteker == null)
        return;
        try{
            inputKosongApotekerException();
            
            int dialog = JOptionPane.showConfirmDialog(rootPane, "Yakin ingin menambahkan Apoteker?");
            if(dialog != JOptionPane.YES_OPTION) return;

            switch(actionApoteker){
                case "add":
                    a = new Apoteker(namaApotekerInputTextField.getText(), emailApotekerInputTextField.getText(), Integer.parseInt(gajiInputTextField.getText()));
                    ac.insertDataApoteker(a);
                    clearTextApoteker();
                    setEditDeleteButtonApoteker(false);
                    setComponentsApoteker(false);
                    break;
                case "update":
                    a = new Apoteker(namaApotekerInputTextField.getText(), emailApotekerInputTextField.getText(), Integer.parseInt(gajiInputTextField.getText()));
                    ac.updateDataApoteker(a, idApoteker);
                    clearTextApoteker();
                    setEditDeleteButtonApoteker(false);
                    setComponentsApoteker(false);
                    break;
                default:
                    break;
            }
            showApoteker();
            actionApoteker = null;
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Input Gaji Harus Berupa Angka!");
        }
    }//GEN-LAST:event_simpanApotekerButtonActionPerformed

    private void searchApotekerInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchApotekerInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchApotekerInputTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel apotekerButtonPanel;
    private javax.swing.JPanel apotekerFormPanel;
    private javax.swing.JLabel apotekerIcon;
    private javax.swing.JLabel apotekerLabel;
    private javax.swing.JPanel apotekerPanel;
    private javax.swing.JScrollPane apotekerScrollPane;
    private javax.swing.JTextArea apotekerTextArea;
    private javax.swing.JButton barukanApotekerButton;
    private javax.swing.JLabel emailApotekerInputLabel;
    private javax.swing.JPanel emailApotekerInputPanel;
    private javax.swing.JTextField emailApotekerInputTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel gajiInputLabel;
    private javax.swing.JPanel gajiInputPanel;
    private javax.swing.JTextField gajiInputTextField;
    private javax.swing.JButton hapusApotekerButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel ketentuanLabel;
    private javax.swing.JLabel ketentuanLabel1;
    private javax.swing.JLabel ketentuanLabel2;
    private javax.swing.JPanel ketentuanPanel;
    private javax.swing.JLabel namaApotekerInputLabel;
    private javax.swing.JTextField namaApotekerInputTextField;
    private javax.swing.JPanel namaApotekerPanel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton searchApotekerInputButton;
    private javax.swing.JLabel searchApotekerInputLabel;
    private javax.swing.JPanel searchApotekerInputPanel;
    private javax.swing.JTextField searchApotekerInputTextField;
    private javax.swing.JButton simpanApotekerButton;
    private javax.swing.JButton tambahApotekerButton;
    // End of variables declaration//GEN-END:variables
}
