package view;

import panelView.*;
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Apoteker;

public class ApotekMainFrame extends javax.swing.JFrame {
    private int selectedIndex = -1;
    private Apoteker loginApoteker; // Atribut untuk menyimpan Apoteker yang login
    
    public ApotekMainFrame(Apoteker loginApoteker) {
        initComponents();
        recolorDefaultSwitchPanel();
        this.loginApoteker = loginApoteker;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void setForm(JComponent com){
        contentPanel.removeAll();
        contentPanel.add(com);
        contentPanel.repaint();
        contentPanel.revalidate();
    }
    
    private void recolorDefaultSwitchPanel(){
        repaint();
        apotekerPanel.setBackground(new Color(0, 0, 0, 0));
        pelangganPanel.setBackground(new Color(0, 0, 0, 0));
        produkPanel.setBackground(new Color(0, 0, 0, 0));
        transaksiPanel.setBackground(new Color(0, 0, 0, 0));
        resepPanel.setBackground(new Color(0, 0, 0, 0));
    }

    public Apoteker getLoginApoteker() {
        return loginApoteker;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        apotekerPanel = new javax.swing.JPanel();
        apotekerLabel = new javax.swing.JLabel();
        apotekerIcon = new javax.swing.JLabel();
        pelangganPanel = new javax.swing.JPanel();
        pelangganLabel = new javax.swing.JLabel();
        pelangganIcon = new javax.swing.JLabel();
        produkPanel = new javax.swing.JPanel();
        produkLabel = new javax.swing.JLabel();
        produkIcon = new javax.swing.JLabel();
        transaksiPanel = new javax.swing.JPanel();
        transaksiLabel = new javax.swing.JLabel();
        transaksiIcon = new javax.swing.JLabel();
        resepPanel = new javax.swing.JPanel();
        resepLabel = new javax.swing.JLabel();
        resepIcon = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        logoIcon = new javax.swing.JLabel();
        apotekLabel2 = new javax.swing.JLabel();
        apotekLabel = new javax.swing.JLabel();
        laporanButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(24, 170, 176));

        headerPanel.setBackground(new java.awt.Color(24, 170, 176));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        menuLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(255, 255, 255));
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuLabel.setText("MENU :");

        apotekerPanel.setBackground(new java.awt.Color(134, 196, 66));
        apotekerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apotekerPanelMouseClicked(evt);
            }
        });

        apotekerLabel.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        apotekerLabel.setForeground(new java.awt.Color(255, 255, 255));
        apotekerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apotekerLabel.setText("Apoteker");

        apotekerIcon.setBackground(new java.awt.Color(255, 255, 255));
        apotekerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apotekerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Apoteker.png"))); // NOI18N

        javax.swing.GroupLayout apotekerPanelLayout = new javax.swing.GroupLayout(apotekerPanel);
        apotekerPanel.setLayout(apotekerPanelLayout);
        apotekerPanelLayout.setHorizontalGroup(
            apotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apotekerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(apotekerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apotekerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        apotekerPanelLayout.setVerticalGroup(
            apotekerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apotekerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(apotekerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pelangganPanel.setBackground(new java.awt.Color(134, 196, 66));
        pelangganPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelangganPanelMouseClicked(evt);
            }
        });

        pelangganLabel.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        pelangganLabel.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pelangganLabel.setText("Pelanggan");

        pelangganIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pelanggan.png"))); // NOI18N

        javax.swing.GroupLayout pelangganPanelLayout = new javax.swing.GroupLayout(pelangganPanel);
        pelangganPanel.setLayout(pelangganPanelLayout);
        pelangganPanelLayout.setHorizontalGroup(
            pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pelangganPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pelangganIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pelangganLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pelangganPanelLayout.setVerticalGroup(
            pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pelangganIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(pelangganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        produkPanel.setBackground(new java.awt.Color(134, 196, 66));
        produkPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produkPanelMouseClicked(evt);
            }
        });

        produkLabel.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        produkLabel.setForeground(new java.awt.Color(255, 255, 255));
        produkLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        produkLabel.setText("Produk");

        produkIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Produk.png"))); // NOI18N

        javax.swing.GroupLayout produkPanelLayout = new javax.swing.GroupLayout(produkPanel);
        produkPanel.setLayout(produkPanelLayout);
        produkPanelLayout.setHorizontalGroup(
            produkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(produkIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(produkLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        produkPanelLayout.setVerticalGroup(
            produkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(produkIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(produkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        transaksiPanel.setBackground(new java.awt.Color(134, 196, 66));
        transaksiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiPanelMouseClicked(evt);
            }
        });

        transaksiLabel.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        transaksiLabel.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transaksiLabel.setText("Transaksi");

        transaksiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Transaksi.png"))); // NOI18N

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(transaksiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(transaksiLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(transaksiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        resepPanel.setBackground(new java.awt.Color(134, 196, 66));
        resepPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resepPanelMouseClicked(evt);
            }
        });

        resepLabel.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        resepLabel.setForeground(new java.awt.Color(255, 255, 255));
        resepLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resepLabel.setText("Pembuatan Resep");

        resepIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PembuatanResep.png"))); // NOI18N

        javax.swing.GroupLayout resepPanelLayout = new javax.swing.GroupLayout(resepPanel);
        resepPanel.setLayout(resepPanelLayout);
        resepPanelLayout.setHorizontalGroup(
            resepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resepPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(resepIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resepLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resepPanelLayout.setVerticalGroup(
            resepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(resepIcon)
        );

        logoutButton.setBackground(new java.awt.Color(241, 53, 21));
        logoutButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        logoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Apotek Side Panel.png"))); // NOI18N

        apotekLabel2.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        apotekLabel2.setForeground(new java.awt.Color(255, 255, 255));
        apotekLabel2.setText("APOTEK");

        apotekLabel.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        apotekLabel.setForeground(new java.awt.Color(134, 196, 66));
        apotekLabel.setText("ASEAN");

        laporanButton.setBackground(new java.awt.Color(134, 196, 66));
        laporanButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        laporanButton.setForeground(new java.awt.Color(255, 255, 255));
        laporanButton.setText("Laporan");
        laporanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanButtonMouseClicked(evt);
            }
        });
        laporanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(menuLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apotekerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pelangganPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(produkPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(apotekLabel)
                                            .addComponent(apotekLabel2))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(laporanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resepPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(108, 108, 108)
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apotekLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apotekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apotekerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pelangganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resepPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        contentPanel.setBackground(new java.awt.Color(134, 196, 66));
        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apotekerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apotekerPanelMouseClicked
        if (selectedIndex == 1) return;
        
        recolorDefaultSwitchPanel();
        apotekerPanel.setBackground(new Color(134, 196, 66, 200));
        setForm(new PanelApoteker(loginApoteker));
        selectedIndex = 1;
    }//GEN-LAST:event_apotekerPanelMouseClicked

    private void pelangganPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelangganPanelMouseClicked
        if (selectedIndex == 2) return;
        
        recolorDefaultSwitchPanel();
        pelangganPanel.setBackground(new Color(134, 196, 66, 200));
        setForm(new PanelPelanggan());
        selectedIndex = 2;
    }//GEN-LAST:event_pelangganPanelMouseClicked

    private void produkPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produkPanelMouseClicked
        if (selectedIndex == 3) return;
        
        recolorDefaultSwitchPanel();
        produkPanel.setBackground(new Color(134, 196, 66, 200));
        setForm(new PanelProduk());
        selectedIndex = 3;
    }//GEN-LAST:event_produkPanelMouseClicked

    private void transaksiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiPanelMouseClicked
        if (selectedIndex == 4) return;
        
        recolorDefaultSwitchPanel();
        transaksiPanel.setBackground(new Color(134, 196, 66, 200));
        setForm(new PanelTransaksi(loginApoteker));
        selectedIndex = 4;
    }//GEN-LAST:event_transaksiPanelMouseClicked

    private void resepPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resepPanelMouseClicked
        if (selectedIndex == 5) return;
        
        recolorDefaultSwitchPanel();
        resepPanel.setBackground(new Color(134, 196, 66, 200));
        setForm(new PanelPembuatanResep(loginApoteker));
        selectedIndex = 5;
    }//GEN-LAST:event_resepPanelMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        int konfirmasi = JOptionPane.showConfirmDialog( this, "Anda yakin ingin logout?", "Konfirmasi Logout", 
               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
        );
       
        if (konfirmasi == JOptionPane.YES_OPTION) {
            this.dispose();
            LoginFrame balik = new LoginFrame();
            balik.setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        logoutButtonMouseClicked(null);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void laporanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanButtonMouseClicked
        if (selectedIndex == 6) return;
        
        recolorDefaultSwitchPanel();
        setForm(new PanelLaporan());
        selectedIndex = 6;
    }//GEN-LAST:event_laporanButtonMouseClicked

    private void laporanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanButtonActionPerformed
        laporanButtonMouseClicked(null);
    }//GEN-LAST:event_laporanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApotekMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApotekMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApotekMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApotekMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApotekMainFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apotekLabel;
    private javax.swing.JLabel apotekLabel2;
    private javax.swing.JLabel apotekerIcon;
    private javax.swing.JLabel apotekerLabel;
    private javax.swing.JPanel apotekerPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton laporanButton;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JLabel pelangganIcon;
    private javax.swing.JLabel pelangganLabel;
    private javax.swing.JPanel pelangganPanel;
    private javax.swing.JLabel produkIcon;
    private javax.swing.JLabel produkLabel;
    private javax.swing.JPanel produkPanel;
    private javax.swing.JLabel resepIcon;
    private javax.swing.JLabel resepLabel;
    private javax.swing.JPanel resepPanel;
    private javax.swing.JLabel transaksiIcon;
    private javax.swing.JLabel transaksiLabel;
    private javax.swing.JPanel transaksiPanel;
    // End of variables declaration//GEN-END:variables
}
