package view;

import panelView.*;
import java.util.List;
import java.util.ArrayList;
import controller.ApotekerControl;
import exception.LoginGagalException;
import model.Apoteker;
import javax.swing.JOptionPane;
import java.awt.Component;
import java.awt.BorderLayout;

public class LoginFrame extends javax.swing.JFrame {
    private ApotekerControl ac;
    List<Apoteker> listApoteker;
    
    private Component rootPane; // untuk memanggil dialog peringatan yg akan digunakan
    
    // Konstruktor
    public LoginFrame() {
        initComponents();   
        setLayout(new BorderLayout());
        add(loginPanel, BorderLayout.CENTER);
        
        ac = new ApotekerControl();
        setApotekerToDropdown();
        
        // RESET
        clearText();
        setComponents(true);
        setExtendedState(LoginFrame.MAXIMIZED_BOTH);
    }
    
    // DROPDOWN Apoteker
    public void setApotekerToDropdown(){
        listApoteker = ac.showListApoteker();
        System.out.println(listApoteker.size());
        namaApotekerDropdown.removeAllItems(); // Menghilangkan item 1-4
        
        for (Apoteker apoteker : listApoteker) {
            namaApotekerDropdown.addItem(apoteker.getNama_apoteker()); // Menambahkan nama Apoteker ke dropdown
        }
    }
    
    // EXCEPTION
    public void loginGagalException(Apoteker A, String inputUsername, String inputPassword) throws LoginGagalException{
        if (A == null || !A.getUsername().equals(inputUsername) || !A.getPassword().equals(inputPassword))
        {
            // Jika username atau password tidak sesuai dengan yang dimiliki oleh Apoteker A
            throw new LoginGagalException();
        }
    }
    
    // RESET METHOD TO DEFAULT
    public void clearText(){
        namaApotekerDropdown.setSelectedIndex(-1);
        usernameInputTextField.setText("");
        passwordInputPasswordField.setText("");
    }
    
    public void setComponents(boolean value){
        namaApotekerDropdown.setEnabled(value);
        usernameInputTextField.setEnabled(value);
        passwordInputPasswordField.setEnabled(value);
        
        loginButton.setEnabled(value);
    }
    
    // Logika percobaan login
    private void attemptLogin() {
        
        String selectedNamaApoteker = (String) namaApotekerDropdown.getSelectedItem();
        String username = usernameInputTextField.getText();
        String password = new String(passwordInputPasswordField.getPassword()); // Ambil password dari JPasswordField

        Apoteker selectedApoteker = null;
        // Cari objek Apoteker lengkap berdasarkan nama yang dipilih dari list
        for (Apoteker apoteker : listApoteker) {
            if (apoteker.getNama_apoteker().equals(selectedNamaApoteker)) {
                selectedApoteker = apoteker;
                break;
            }
        }

        if (selectedApoteker == null) {
            JOptionPane.showMessageDialog(this, "Apoteker tidak ditemukan di daftar. Harap refresh.", "Error Login", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            Apoteker apoteker = ac.searchApotekerById(selectedApoteker.getId_apoteker());
            loginGagalException(apoteker, username, password);
            
            JOptionPane.showMessageDialog(this, "Selamat datang, Apoteker " + apoteker.getNama_apoteker() + 
                    "!", "Login Berhasil", JOptionPane.INFORMATION_MESSAGE);
            
            // Hapus semua komponen yang saat ini ada di JFrame (komponen UI)
            this.dispose();

            ApotekMainFrame mainAppFrame = new ApotekMainFrame(apoteker);
            mainAppFrame.setVisible(true);
        } catch (LoginGagalException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Login Gagal", JOptionPane.ERROR_MESSAGE);
            passwordInputPasswordField.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    public void resetAndShowLogin(){
        getContentPane().removeAll();
        add(loginPanel, BorderLayout.CENTER);
        clearText();

        setComponents(true);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        apotekIcon = new javax.swing.JLabel();
        apotekLabel = new javax.swing.JLabel();
        pookieLabel = new javax.swing.JLabel();
        inputLoginPanel = new javax.swing.JPanel();
        namaApotekerDropdown = new javax.swing.JComboBox<>();
        usernameLabel = new javax.swing.JLabel();
        akunApotekerLabel = new javax.swing.JLabel();
        usernameInputTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordInputPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1492, 813));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setForeground(new java.awt.Color(255, 255, 255));
        loginPanel.setLayout(null);

        apotekIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apotekIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Apotek Icon.png"))); // NOI18N
        loginPanel.add(apotekIcon);
        apotekIcon.setBounds(250, 180, 295, 311);

        apotekLabel.setFont(new java.awt.Font("Arial Black", 1, 100)); // NOI18N
        apotekLabel.setForeground(new java.awt.Color(134, 196, 66));
        apotekLabel.setText("ASEAN");
        loginPanel.add(apotekLabel);
        apotekLabel.setBounds(590, 310, 403, 91);

        pookieLabel.setFont(new java.awt.Font("Arial Black", 1, 100)); // NOI18N
        pookieLabel.setForeground(new java.awt.Color(24, 170, 176));
        pookieLabel.setText("APOTEK");
        loginPanel.add(pookieLabel);
        pookieLabel.setBounds(590, 210, 484, 88);

        inputLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        inputLoginPanel.setForeground(new java.awt.Color(255, 255, 255));

        namaApotekerDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        usernameLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(24, 170, 176));
        usernameLabel.setText("Masukkan Username");

        akunApotekerLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        akunApotekerLabel.setForeground(new java.awt.Color(24, 170, 176));
        akunApotekerLabel.setText("Pilih akun Apoteker :");

        passwordLabel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(24, 170, 176));
        passwordLabel.setText("Masukkan Password");

        javax.swing.GroupLayout inputLoginPanelLayout = new javax.swing.GroupLayout(inputLoginPanel);
        inputLoginPanel.setLayout(inputLoginPanelLayout);
        inputLoginPanelLayout.setHorizontalGroup(
            inputLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputLoginPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(inputLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordInputPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inputLoginPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(inputLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(inputLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(akunApotekerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namaApotekerDropdown, 0, 361, Short.MAX_VALUE)
                                .addComponent(usernameInputTextField))))))
        );
        inputLoginPanelLayout.setVerticalGroup(
            inputLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(akunApotekerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaApotekerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInputPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginPanel.add(inputLoginPanel);
        inputLoginPanel.setBounds(560, 450, 390, 240);

        loginButton.setBackground(new java.awt.Color(24, 170, 176));
        loginButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton);
        loginButton.setBounds(990, 590, 140, 60);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Background LoginFrame.png"))); // NOI18N
        loginPanel.add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1550, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        attemptLogin();
    }//GEN-LAST:event_loginButtonMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akunApotekerLabel;
    private javax.swing.JLabel apotekIcon;
    private javax.swing.JLabel apotekLabel;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JPanel inputLoginPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JComboBox<String> namaApotekerDropdown;
    private javax.swing.JPasswordField passwordInputPasswordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel pookieLabel;
    private javax.swing.JTextField usernameInputTextField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
